apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 192.168.68.10-192.168.68.49 # Specify your range or subnet 192.168.68.0/26
