apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default # default is fine for each cluster that has the metallb-system namespace.  Rename if running multiple pools within the same namespace and same cluster.
  namespace: metallb-system
spec:
  addresses:
  - 192.168.71.200-192.168.71.250 # Specify your range or subnet 192.168.71.0/26
